CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
    brand_name VARCHAR(255) NOT NULL,
    created_date timestamp NOT NULL,
    updated_date timestamp ,
    deleted_date timestamp
);
 CREATE TABLE IF NOT EXISTS products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    price BIGINT,
    brand_id BIGINT,
    created_date timestamp NOT NULL,
    updated_date timestamp ,
    deleted_date timestamp,
    FOREIGN KEY (brand_id) REFERENCES brands(id)
 );